databases:
  - name: budget-app
    databaseName: budget_app_afmk
    user: budget_app_afmk_user

services:
  - type: web
    name: data-sync
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_afmk
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false